/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package it.uniba.app;

/**
 * Main class of the application.
 */
public final class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(final String[] args) {
        System.out.println(new App().getGreeting());
    }
}
